In [2]:
import pandas as pd 
import os
import datetime
from datetime import datetime
import warnings

In [3]:
warnings.filterwarnings('ignore')

#### ส่วนจัดการไฟล์

In [4]:
#เปลี่ยน path
path = r'C:\Users\charoenchai.chu\Desktop\Rules\สาขาแม่ฮ่องสอน และสาขาแม่สะเรียง'
file_name00 = 'IND_421'

file_path00 = os.path.join(path, file_name00 + '.xlsx')
df0=pd.read_excel(file_path00 , skiprows= 4)
df0['รหัสสาขา'] = file_name00[-3:]

In [5]:
#เปลี่ยน path
path = r'C:\Users\charoenchai.chu\Desktop\Rules\สาขาแม่ฮ่องสอน และสาขาแม่สะเรียง'
file_name01 = 'IND_422'

file_path01 = os.path.join(path, file_name01 + '.xlsx')
df1=pd.read_excel(file_path01 , skiprows= 4)
df1['รหัสสาขา'] = file_name01[-3:]

In [6]:
df = pd.concat([df0, df1], ignore_index=True)

In [7]:
# ตั้งชื่อ field ใหม่ทั้งหมด
new_column_names = ['ที่', 'กรมธรรม์', 'ชื่อ-สกุล', 'ที่อยู่1', 'วันที่จ่ายเงิน', 'ปี','จำนวนเงิน' ,'รับเอง' ,'รับมอบฯ' ,'null','รหัสสาขา']
df.columns = new_column_names
# แทนที่ค่า null ด้วยตัวก่อนหน้า

df['กรมธรรม์'] = df['กรมธรรม์'].astype(str)
length = df['กรมธรรม์'].str.len()
df['กรมธรรม์'] = df['กรมธรรม์'].where(length >= 6, df['กรมธรรม์'].shift())
# เปลี่ยน type ข้อมูล
dtypes = {
        "ที่": "str",
        "กรมธรรม์": "str",
        "รหัสสาขา": "str",
        "ชื่อ-สกุล": "object",
        "ที่อยู่1": "object", 
        # "ที่อยู่2": "object",
        "วันที่จ่ายเงิน": "object",
        "ปี": "object",
        "จำนวนเงิน": "str",
        "รับเอง": "object",
        "รับมอบฯ": "object"
    }
df = df.astype(dtypes)
# ตัดแถวว่างออก
df = df[df['ที่อยู่1'] . notnull()]
df.head()

,ที่,กรมธรรม์,ชื่อ-สกุล,ที่อยู่1,วันที่จ่ายเงิน,ปี,จำนวนเงิน,รับเอง,รับมอบฯ,null,รหัสสาขา
1,1,42302745,นายสนอง พันธ์พนากร,521 หมู่ที่ 1 หมู่บ้านขุนยวม,20/09/2566,08/66,"11,279",NaN,/,NaN,421
2,nan,42302745,โทร.,ต.ขุนยวม อ.ขุนยวม จ.แม่ฮ่องสอน 58140,NaN,NaN,nan,NaN,NaN,NaN,421
4,2,42302614,นายจินดนัย ปันทวัง,111/2 หมู่ที่ 2,04/11/2566,07/66,"53,243",/,NaN,NaN,421
5,nan,42302614,โทร.,ต.แม่ยวม อ.แม่สะเรียง จ.แม่ฮ่องสอน 58110,NaN,NaN,nan,NaN,NaN,NaN,421
7,3,42302613,นายจักรินทร์ ปันทวัง,111/2 หมู่ที่ 2,07/11/2566,07/66,"54,172",/,NaN,NaN,421

In [8]:
# เอาที่เลขกรมธรรม์เป็น null ออก เอาไว้ไปเติมข้อมูล
null_df = df[df['วันที่จ่ายเงิน'] . isnull()]
null_df.head()
null_field = ['กรมธรรม์' , 'ที่อยู่1']
null_df = null_df[null_field]
# เปลี่ยนชื่อ field
null_df.columns = ['กรมธรรม์' , 'ที่อยู่2']
# null_df.head()

In [9]:
# ดึงเลขกรมธรรม์ที่ไม่ null
notnull_df = df[df['วันที่จ่ายเงิน'] .notnull()]
# notnull_df.head()

In [10]:
# ่join data
data_df = pd.merge(notnull_df, null_df, on='กรมธรรม์', how='left')

# เรียงลำดับคอลัมน์ใหม่ 
column_order = ['ที่', 'กรมธรรม์','รหัสสาขา' , 'ชื่อ-สกุล', 'ที่อยู่1', 'ที่อยู่2', 'วันที่จ่ายเงิน', 'ปี','จำนวนเงิน' ,'รับเอง' ,'รับมอบฯ' ,'null']
data_df = data_df[column_order]

# ตัด culumn null ออก
data_df = data_df[['ที่', 'กรมธรรม์','รหัสสาขา' , 'ชื่อ-สกุล', 'ที่อยู่1', 'ที่อยู่2', 'วันที่จ่ายเงิน', 'ปี','จำนวนเงิน' ,'รับเอง' ,'รับมอบฯ']]

data_df.head()

,ที่,กรมธรรม์,รหัสสาขา,ชื่อ-สกุล,ที่อยู่1,ที่อยู่2,วันที่จ่ายเงิน,ปี,จำนวนเงิน,รับเอง,รับมอบฯ
0,1,42302745,421,นายสนอง พันธ์พนากร,521 หมู่ที่ 1 หมู่บ้านขุนยวม,ต.ขุนยวม อ.ขุนยวม จ.แม่ฮ่องสอน 58140,20/09/2566,08/66,"11,279",NaN,/
1,2,42302614,421,นายจินดนัย ปันทวัง,111/2 หมู่ที่ 2,ต.แม่ยวม อ.แม่สะเรียง จ.แม่ฮ่องสอน 58110,04/11/2566,07/66,"53,243",/,NaN
2,3,42302613,421,นายจักรินทร์ ปันทวัง,111/2 หมู่ที่ 2,ต.แม่ยวม อ.แม่สะเรียง จ.แม่ฮ่องสอน 58110,07/11/2566,07/66,"54,172",/,NaN
3,4,42302743,421,นางกฤชญา ปัญญาธรรม,246 หมู่ที่ 1 หมู่บ้านผาบ่อง,ต.ผาบ่อง อ.เมือง จ.แม่ฮ่องสอน 58000,05/01/2567,11/66,"14,076",/,NaN
4,5,44049556,421,ด.ช.พีรวัส อริทะ,165 หมู่ที่ 4 หมู่บ้านนาป่าแปก,ต.หมอกจำแป่ อ.เมือง จ.แม่ฮ่องสอน 58000,11/01/2567,02/67,"10,611",NaN,/

In [195]:
# ตัดแถวที่ไม่ต้องการ
data_df_finish = data_df[data_df['ปี'] .notnull()]
# notnull_df = df[df['กรมธรรม์'] .notnull()]
# data_df_finish.head()

In [196]:
data_df_finish['จำนวนเงิน'] = data_df_finish['จำนวนเงิน'].str.replace(',', '').astype(int)
data_df_finish = data_df_finish.sort_values(by=['รหัสสาขา', 'จำนวนเงิน'], ascending=[True, False])

#### ส่วน ACL

In [197]:
Rule_IND_df = data_df_finish[data_df_finish['รับมอบฯ'] == '/']
# เรียงลำดับ รหัสสาขา กับ จำนวนเงิน 
Rule_IND_df = Rule_IND_df.sort_values(by=['รหัสสาขา', 'จำนวนเงิน'], ascending=[True, False])
Rule_IND_df.head()

,ที่,กรมธรรม์,รหัสสาขา,ชื่อ-สกุล,ที่อยู่1,ที่อยู่2,วันที่จ่ายเงิน,ปี,จำนวนเงิน,รับเอง,รับมอบฯ
0,1,42302745,421,นายสนอง พันธ์พนากร,521 หมู่ที่ 1 หมู่บ้านขุนยวม,ต.ขุนยวม อ.ขุนยวม จ.แม่ฮ่องสอน 58140,20/09/2566,08/66,11279,NaN,/
4,5,44049556,421,ด.ช.พีรวัส อริทะ,165 หมู่ที่ 4 หมู่บ้านนาป่าแปก,ต.หมอกจำแป่ อ.เมือง จ.แม่ฮ่องสอน 58000,11/01/2567,02/67,10611,NaN,/
5,6,44049558,421,ด.ช.พีรวิชญ์ อริทะ,165 หมู่ที่ 4 หมู่บ้านนาป่าแปก,ต.หมอกจำแป่ อ.เมือง จ.แม่ฮ่องสอน 58000,11/01/2567,02/67,10611,NaN,/
30,19,42415237,422,ด.ช.กษิดิ์เดช นันไชย,105 หมู่ที่ 1 บ้านน้ำดิบ,ต.แม่ยวม อ.แม่สะเรียง จ.แม่ฮ่องสอน 58110,26/06/2567,04/67,19382,NaN,/

##### Export

In [198]:
# วันที่ปัจจุบัน
now = datetime.now().strftime("%Y%m%d")

# แยก DataFrame ตามรหัสสาขาและบันทึกไฟล์ Excel
grouped = Rule_IND_df.groupby('รหัสสาขา')

for รหัสสาขา, group in grouped:
    # จำกัดจำนวน record ไม่เกิน 5
    if len(group) > 5:
        group = group.iloc[:5]
    record_count = group.shape[0]  # นับจำนวน record หลังการแบ่งไฟล์
    output_file_name = f"OPsurrenderIND_{รหัสสาขา}_รับมอบ_{now}_{record_count}.xlsx"
    file_path = os.path.join(path, output_file_name)
    group.to_excel(file_path, index=False)